Allow messages without text
mattermost/action-mattermost-notify pull request #6
Opened 2020-03-28 19:28 UTC by hanzei

#### Summary
- Allow messages without text
- Cleanup go.mod and go.sum
- Bump go version
- Bump version

#### Ticket Link
https://github.com/mattermost/mattermost-developer-documentation/pull/569#issuecomment-602806852

2020-03-30 08:40 UTC, metanerd requested changes
Nice catch! 
Would this have happened with tests? Maybe we can add some?

2020-03-30 17:29 UTC, hanzei commented
@metanerd Thanks for the suggestion. I've added some :+1:

2020-03-30 17:32 UTC, metanerd approved these changes
Looks very good to me!

2020-03-31 15:13 UTC, cpanato approved these changes

2020-03-31 15:13 UTC, merged